### PR TITLE
Add getEventNearestToTimestamp

### PR DESCRIPTION
**Pull request by Half-Shot**
Needs #37 to fix the diffs

## Checklist

* [ ] Tests written for all new code
* [ ] Linter has been satisfied
* [ ] Sign-off given on the changes (see CONTRIBUTING.md)

### CODE REVIEW

**Review by AndrewFerr — DISMISSED** [review]

**Comment by AndrewFerr** [comment]
https://github.com/Half-Shot/matrix-bot-sdk/pull/1

**Comment by AndrewFerr** [comment]
> [557b39c](https://github.com/vector-im/matrix-bot-sdk/pull/38/commits/557b39c6704f91dd805f4b2fded10bad10377d10)

IMO it's better to not merge with `vector-im:main` & to instead keep this branch relative to upstream's main, as it can be more easily merged into both repos that way, which is worth doing since this PR is useful for upstream too.  In fact, doing that makes it possible to open an upstream PR with the same branch as this one.

**Comment by Half-Shot** [comment]
Apparently it was a requirement on the repo to keep this branch up to date with main.

**Comment by AndrewFerr** [comment]
> Apparently it was a requirement on the repo to keep this branch up to date with main.

It technically isn't, but it makes reading through commit history & keeping up-to-date with upstream _so_ much easier.

I've updated https://github.com/Half-Shot/matrix-bot-sdk/pull/1 with a version of this PR with commits shifted onto upstream main, which I would very much appreciate being done here (I'd have done it myself but this PR is on a repo I don't have write access on).

**Review by AndrewFerr — APPROVED** [review]

**Pull request merged**
